package jp.daich.diffsellect.poi.book.style.constants;

public enum StyleMapKey {
    NORMAL,
    SMALL_TEXT,
    RANGE_BOX_LEFT_TOP,
    RANGE_BOX_LEFT_MIDDLE,
    RANGE_BOX_LEFT_BOTTOM,
    RANGE_BOX_MIDDLE_TOP,
    RANGE_BOX_MIDDLE_MIDDLE,
    RANGE_BOX_MIDDLE_BOTTOM,
    RANGE_BOX_RIGHT_TOP,
    RANGE_BOX_RIGHT_MIDDLE,
    RANGE_BOX_RIGHT_BOTTOM,
    RANGE_BOX_ONE_COLUMN_TOP,
    RANGE_BOX_ONE_COLUMN_MIDDLE,
    RANGE_BOX_ONE_COLUMN_BOTTOM;
}
